### ISSUE TITLE
Using an existing secret

### ISSUE THREAD

**Issue by jdblack** [suda/k8s-ovpn-chart#4]
Hi there!   I'm rather new to k8s, so forgive me for any silly questions :)

Is there a way to use an existing secret, rather  than have openvpn generate one?  I have cert-man running a local ca and already have a way to generate   certs+secrets for openvpn  that I would like for it to consume.

**Comment by suda** [comment]
Hi James! Yes, the [`generate-config`](https://github.com/suda/k8s-ovpn-chart/blob/master/bin/generate-config) script generates all the secrets but it's the [`set-secrets`](https://github.com/suda/k8s-ovpn-chart/blob/master/bin/set-secrets) that sets them in Kubernetes. So if you already have configuration you cold:
1. Run `./bin/generate-config`
2. Replace generated config with your own
3. Run `./bin/set-secrets` to set the Kubernetes secrets

**Comment by jdblack** [comment]
Ahh, yes.   certificate manager has a different format.  cert manager makes a single secret file that contains, ca cert, tls cert and tls key.   

I ended up making something new here:  https://github.com/jdblack/openvpn_k8s

Thank you very much!
