### ISSUE TITLE
Restrict access to a specific namespace

### ISSUE THREAD

**Issue by shibumi** [suda/k8s-ovpn-chart#5]
Hi,
I don't know if I understand your Readme correct.
Is it possible to restrict access from OpenVPN clients to a specific namespace?

What I basically want to do is: OpenVPN client connects to namespace "OpenVPN". Inside of "OpenVPN" I have a few other services running.. let's say a website only this clients should access. Is it possible to restrict access to this specific namespace? What I really don't want is: Exposing my whole cluster via VPN. So the openVPN client should not be able to connect to other namespaces such like "Default" or "project-X" or "My-Evil-Plan-Namespace" :D

**Comment by suda** [comment]
Hi Christian! That would be against the goal of this specific chart. I wanted to have an OpenVPN installation that **does not** have access to the cluster (kind of "roll your own NordVPN"). If you want secure access to a particular namespace, I think [this chart would work better](https://github.com/helm/charts/tree/master/stable/openvpn) :)

**Comment by shibumi** [comment]
Thanks @suda, we ran into some problems with your linked chart, so I hoped yours may be a good fit :D
